CafeShop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls', namespace='menu')),
    path('', include('dashboard.urls')),
    path('', include('home.urls')),
    path('userprofile/', include('userprofile.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import include, re_path, path
from django.conf import settings 
from django.conf.urls.static import static
from django.views.generic import DetailView
from django.contrib.auth import views as auth_views

from home import views as home_view
from . import views
from home.views import *

from userprofile import views as userprofile_view
from . import views
from userprofile.views import *

app_name = 'home'
urlpatterns = [
  re_path('^index/$', home_view.index, name='index'),
    re_path('^home/$', home_view.home, name='home'),
    re_path('^test/$', home_view.test, name='test'),
    re_path('^aboutus/$', home_view.aboutus, name='aboutus'),
    re_path('^findus/$', home_view.FindUs, name='findus'),
    re_path('^drinks/$',home_view.drinks,name='drinkpage'),
    re_path('^hottea/$',home_view.hottea,name='hotcoffee'),
    re_path('^profile/$', home_view.profile, name='profile'),
    re_path('^favoritedrinks/$', home_view.favdrink, name='favoritedrink'),
    re_path('^previousorder/$', home_view.previousorder, name='previousorder'),
    path('update_profile_picture/', views.update_profile_picture, name='update_profile_picture'),
    path('delete_profile_picture/', views.delete_profile_picture, name='delete_profile_picture'),
    # path('edit_user_info/', views.edit_user_info, name='edit_user_info'),
    # path('update_profile_info/', views.update_profile_info, name='update_profile_info'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

menu/urls.py
from django.urls import include, re_path
from django.conf import settings 
from django.conf.urls.static import static
from django.views.generic import *
from django.urls import path
from django.contrib.auth import views as auth_views

from menu import views as menu_view
from . import views
from menu.views import *



app_name = 'menu'
urlpatterns = [
    re_path('menu/', views.menu, name='menu'),
    path('drink_details/<int:product_id>/', views.drink_details, name='drink_details'),
    path('order-details/', views.order_detail_list, name='order_detail_list'),
    path('order-details/<int:order_detail_id>/', views.order_detail_detail, name='order_detail_detail'),
    path('iced-drinks/', views.iced_drinks, name='IcedDrink'),
    path('hot-drinks/', views.hot_drinks, name='HotDrink'),
    path('frappe-drinks/', views.frappe_drinks, name='FrappeDrink'),
    path('add_to_order/', views.add_to_order, name='add_to_order'),
    path('cart/', views.cart, name='cart'),
    path('user_detail/', views.user_detail, name='user_detail'),
    path('checkout/', views.checkout, name='checkout'),
    path('confirm_order/', views.confirm_order, name='confirm_order'),
    path('order_confirmation/', views.order_confirmation_page, name='order_confirmation_page'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('continue-to-order/', views.continue_to_order, name='continue_to_order'),
    path('remove_product_from_order/<int:cart_item_id>/', views.remove_product_from_order, name='remove_product_from_order'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CafeShop/templates/Orderfolder/cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cart</title>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@700&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.17/dist/sweetalert2.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.17/dist/sweetalert2.all.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<style>
    * {
        margin: 0;
        padding: 0;
    }

    body {
        font-family: var(--primary-font);
        font-weight: bold;
    }

    :root {
        --primary-font: "Quicksand", sans-serif;
        --secondary-font: "Poppins", sans-serif;
        --first-color: #fffdd0;
        --second-color: #a0522d;
    }

    .confirmpage {
        width: 100%;
        display: flex;
    }

    .confirmpage .blocka {
        width: 50%;
        background-color: #A0522D;
        color: white;
    }

    .confirmpage .blocka .conlogo {
        width: 8%;
    }

    .taghead {
        display: flex;
        align-items: center;
        margin: 4% 0% 0% 5%;
    }

    .taghead a {
        width: 15%;
    }

    .taghead a img {
        width: 100%;
        max-width: 200px;
    }

    .taghead h1 {
        margin-left: 1%;
    }

    .taghead h1 a {
        text-decoration: none;
        color: white;
    }

    .tagbody {
        display: flex;
        flex-direction: column;
        margin: 40% 0% 0% 5%;
    }

    .tagbody h1 {
        font-size: 55px;
    }

    .tagbody h2 a {
        color: white;
    }

    .tagbody h2 {
        color: #BCC4C2;
    }

    footer {
        padding: 0;
        margin: 0;
        width: 100%;
        background-color: #F9F9F9;
    }

    footer .col {
        border-top: 1px solid #9B8888;
        border-bottom: 1px solid #9B8888;
        display: flex;
        padding: 4% 0% 6% 3%;
        margin-bottom: 5px;
    }

    footer .col .col2 {
        margin-left: 5%;
    }

    footer .col .col3 {
        margin-left: 5%;
    }

    footer .col .col4 {
        margin-left: 5%;
    }

    footer .col .col5 {
        margin-left: 5%;
    }

    footer .col h2 {
        color: #A0522D;
    }

    footer .footericon {
        display: flex;
    }

    footer .footericon img {
        width: 35px;
        height: 35px;
        border-radius: 50%;
        margin-left: 25px;
    }

    footer .footerlink ul {
        list-style: none;
        display: flex;
        margin-top: 4%;
    }

    footer .footerlink ul li a {
        color: black;
        text-decoration: none;
        margin-right: 25px;
    }

    footer p {
        color: #A0522D;
        margin-top: 4%;
        margin-left: 25px;
    }

    .blockbodyahti2 {
        width: 50%;
        background-color: #F9F9F9;
        overflow-y: auto;
        margin-top: 5vh;
        margin-left: 5vh;
    }

    .blockbodyahti2 .cofebox {
        box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
        justify-content: space-around;
        max-height: 80vh;
        overflow-y: auto;

    }

    /* Add media query for smaller screens */
    @media screen and (max-width: 768px) {

        .confirmpage .blocka,
        .blockbodyahti2 {
            width: 100%;
        }

        .taghead a img {
            max-width: 150px;
        }
    }



    .order-container {
        display: flex;
        flex-wrap: wrap;
        background-color: white;
        justify-content: center;
        gap: 35px;

    }


    .product-container {
        width: 30%;
        margin-bottom: 2vh;

    }

    .cofebox {
        height: 600px;
        border-radius: 20px;
        padding-bottom: 5vh;

    }

    .cofebox img {
        width: 100%;
        max-width: 440px;

    }

    /* Add media query for smaller screens to display one item per row */
    @media screen and (max-width: 768px) {
        .product-container {
            width: 100%;
        }
    }

    h1.product-name {
        color: var(--second-color);
        margin-top: 2vh;
        text-align: center;
        font-family: var(--primary-font);
        font-size: 23px;
    }

    i.fa-solid {
        font-size: 10px;
    }

    p.product {
        text-align: center;
        padding: 10px 0;
    }

    p.total-price {
        color: var(--second-color);
    }


    button.continue-button {
        background-color: var(--second-color);
        font-family: var(--second-font);
        border-radius: 25px;
        border: 1px solid black;
        font-size: 20px;
        color: white;
        margin: 5vh 2vh 0 1vh;
        padding: 10px 15px 25px 10px;
        height: 50px;
        float: right;
        cursor: pointer;
        position: relative;
        overflow: hidden;
        transition: background-color 0.5s ease, color 0.5s ease;
        /* Added color transition */
    }

    button.continue-button:hover {
        background-color: black;
        color: white;

    }




    a.go-back-btn {
        padding: 15px;
        border-radius: 15px;
        transition: 0.5s ease-in;
    }

    a.go-back-btn:hover {
        background-color: black;
    }

    button.remove-button {
        transition: 0.3s ease-in;
        display: flex;
        margin: 0 auto;
        padding: 10px;
        background-color: red;
        border-radius: 20px;
        color: white;
        font-family: var(--primary-font);
        border: 1px solid white;
        cursor: pointer;
    }

    button.remove-button:hover {
        background-color: black;
    }

    a.continue-button {
        color: white;
        text-decoration: none;
    }
</style>

<body>
    <div class="confirmpage">
        <div class="blocka">
            <div class="taghead">
                <a href="{% url 'home:index' %}">
                    <img src="{% static 'image/logo/image-removebg-preview__2__auto_x2-removebg-preview.png' %}"
                        alt="Logo" />
                </a>
                <h1><a href="#" onclick="history.go(-1); return false;" class="go-back-btn">&lt; Back to previous
                        page</a></h1>
            </div>
            <div class="tagbody">
                <h1>Review Order ({{ order_details.count }})</h1><br>
                <h2>For item availability</h2>
                <h2><a href="{% url 'home:findus' %}">Choose a store &gt;</a></h2>
            </div>
        </div>
        <div class="blockbodyahti2">
            {% if cart_items %}
            <div class="order-container">
                {% for cart_item in cart_items %}
                <div class="product-container">
                    <div class="cofebox">
                        <img src="{{ cart_item.product_size.images.url }}"
                            alt="{{ cart_item.product_size.product.product_name }}">
                        <div class="cofeinfo">
                            <h1 class="product-name">{{ cart_item.product_size.product.product_name }}</h1>
                            <br><br>
                            <p style="font-size: 20px;" class="product product-size">{{ cart_item.product_size.size}}
                            </p>
                            <p style="font-size: 20px;" class="product product-quantity">Quantity:
                                {{cart_item.quantity}}</p>
                            <p style="font-size: 25px;" class="product total-price">
                                ${{cart_item.calculate_total_price|floatformat:2 }}</p><br><br>

                            <!-- Add a "Remove" button -->
                            <form method="post" action="{% url 'menu:remove_product_from_order' cart_item.id %}">
                                {% csrf_token %}
                                <button type="button" class="remove-button"
                                    data-product-name="{{ cart_item.product_size.product.product_name }}"
                                    data-product-quantity="{{ cart_item.quantity }}"
                                    data-product-size="{{ cart_item.product_size.size }}"
                                    onclick="confirmRemove({{ cart_item.id }})">
                                    Remove
                                </button>
                            </form>


                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:2 and not forloop.last %}
            </div>
            <div class="order-container">
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}

        </div>

        <button class="continue-button"><a href="{% url 'menu:continue_to_order' %}"
                class="continue-button">Continue</a></button>



    </div>




    <footer>
        <div class="col">
            <div class="col1">
                <h2>Careers</h2>
                <p>Culture and Values</p>
                <p>Inclusion, Diversity <br>, and Equity</p>
                <p>College Achievement Plan</p>
                <p>Alumni Community</p>
                <p>International Careers</p>
            </div>

            <div class="col2">
                <h2>People</h2>
                <p>Planet</p>
                <p>Environmental and Social <br> Impact Reporting</p>
            </div>

            <div class="col3">
                <h2>For Business Partners</h2>
                <p>Landlord Support Center</p>
                <p>Suppliers</p>
                <p>Corporate Gift Card Sales</p>
                <p>Office and Foodservice Coffee</p>
            </div>

            <div class="col4">
                <h2>Order and Pick Up</h2>
                <p>Order on the App</p>
                <p>Order on the Web</p>
                <p>Delivery</p>
                <p>Order and Pick Up Options</p>
                <p>Explore and Find Coffee for Home</p>
            </div>
        </div>
        <div class="footericon">
            <img src="{% static 'image/footer/fbicon.png' %}" alt="">
            <img src="{% static 'image/footer/igicon.png' %}" alt="">
            <img src="{% static 'image/footer/pinteresticon.png' %}" alt="">
            <img src="{% static 'image/footer/twittericon.png' %}" alt="">
            <img src="{% static 'image/footer/yticon.png' %}" alt="">
        </div>
        <div class="footerlink">
            <ul>
                <li><a href="#">Privacy Notice |</a></li>
                <li><a href="#">Term of Use | </a></li>
                <li><a href="#">Do Not Share My Personal Information |</a></li>
                <li><a href="#">CA Supply Chain Act |</a></li>
                <li><a href="#">Cookie Preferences |</a></li>
            </ul>
        </div>
        <p>© 2023 Starbucks Coffee Company. All rights reserved.</p>
    </footer>

    <script>
        $(document).ready(function() {
            $('.continue-button').on('click', function() {
        if ($('.product-container').length === 0) {
            Swal.fire({
                icon: 'error',
                title: "There are no products in your basket",
            });
            return false;
        } else {
         
        }
    });
        
            function confirmRemove(orderDetailId) {
                const removeButton = document.querySelector(
                    `button[data-product-name][data-product-quantity][data-product-size][onclick="confirmRemove(${orderDetailId})"]`
                );
                const productName = removeButton.getAttribute('data-product-name');
                const productQuantity = removeButton.getAttribute('data-product-quantity');
                const productSize = removeButton.getAttribute('data-product-size');
        
                if (
                    confirm(
                        `Are you sure you want to remove (${productQuantity}) ${productName} (${productSize} size) from your cart?`
                    )
                ) {
                    const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
        
                    fetch("{% url 'menu:remove_product_from_order' 0 %}".replace('0', orderDetailId), {
                        method: 'POST',
                        headers: {
                            'X-CSRFToken': csrfToken,
                        },
                    })
                        .then((response) => {
                            if (response.status === 200) {
                                // Item removed successfully, display a success message
                                alert('Remove drink success');
                                location.reload();
                            } else {
                                alert('Error removing item from cart.');
                            }
                        })
                        .catch((error) => {
                            console.error('Error:', error);
                            alert('An error occurred while removing the item from the cart.');
                        });
                }
            }
        });
        </script>





</body>

</html>

CafeShop/templates/Orderfolder/checkout.html
{% load static %}
<!DOCTYPE html>
<body lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- <title>{% block title %} Home {% endblock title %}</title> -->
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@700&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- <link rel="stylesheet" href="{% static 'css/menucss2.css' %}" /> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        integrity="sha512-..." crossorigin="anonymous" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"
        integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css"
        href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <link rel="stylesheet" href="custom.css"> -->
    <link rel="stylesheet" href="{% static 'css/checkout.css' %}">
</head>
<style>
    .notification-background {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        display: none;
        z-index: 9998;
    }

    .alert {
        background-color: rgb(0, 161, 27);
        width: 300px;
        border-radius: 20px;
        color: #ffffff;
        text-align: center;
        display: none;
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        padding: 20px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.5);
        z-index: 9999;
    }

    .alert h3,
    .alert h6,
    .alert p {
        margin: 0;
    }

    .alert #okButton {
        background-color: #ffffff;
        color: rgb(0, 161, 27);
        border: none;
        padding: 10px 20px;
        border-radius: 4px;
        cursor: pointer;
        margin-top: 20px;
    }
    .order-item {
        display: flex;
        align-items: center;
        margin-bottom: 20px;
    }

    .order-item-image {
        flex: 1;
    }

    .order-item-image img {
        max-width: 100%;
    }

    .order-item-details {
        flex: 3;
        padding-left: 10px;
    }

    .product-name {
        font-weight: bold;
    }
</style>
<body>
    <div class="container" style="background-color: #ffffff; width:100%; height: 80vh">
        <div class="row">
            {% if user.is_authenticated %}
            <div class="col-md-6" style="background-color: #ffffff; border-radius: 20px;">
                <h1>Checkout</h1>
                <h6>SHIPPING DETAILS</h6>
                <hr>
                <div class="infor" style="padding-bottom: 20px;">
                    <div>Username: {{ customer.user }}</div>
                    <div>Email: {{ user.customer.user.email }}</div>
                    <div>Tel: {{ customer.contact }}</div>
                    <div>House No: {{ customer.house_number }}<br> Road: {{ customer.road }} <br>District: {{ customer.district }}</div>
                </div>
                <h3>Payment Details</h3>
                <div class="payment" style="margin-top: 25px;">
                    <input type="checkbox" id="credit" name="credit"> Credit Card / Debit Card</input>
                </div>
                <div id="card">
                    <!-- Add your credit card input fields here as per your friend's design -->
                </div>
                <div class="payment" style="margin-top: 20px; margin-bottom: 20px;">
                    <input type="checkbox" id="cash" name="cash"> Cash on Delivery
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-truck"
                        viewBox="0 0 16 16">
                        <path
                            d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
                    </svg>
                </div>
                <hr>
                <button id="orderButton"
                    style="background-color: rgb(69, 236, 195); padding: 8px; border-radius: 12px; border: none; font-size: 1.2rem; color: #433a3a; box-shadow: #433a3a;"
                    onclick="validatePayment()">Purchase ${{ total_price }}</button>
                <form method="POST" action="{% url 'menu:confirm_order' %}" id="orderForm" style="display: none;">
                    {% csrf_token %}
                    <input type="hidden" name="total_price" id="totalPriceInput" value="{{ total_price }}">
                </form>
                <hr>
            </div>
            <div class="col-md-6" style="background-color: #ffffff; border-radius: 20px;">
                <div class="row">
                    <div class="col-md-4">
                        <h6>Your Order</h6>
                        <hr>
                        {% for order_detail in order_details %}
                        <div>
                            <img src="{{ order_detail.product_size.images.url }}" style="max-width: 100%;"
                                alt="{{ order_detail.product_size.product.product_name }}">
                            <p>Product Name: {{ order_detail.product_size.product.product_name }}</p>
                            <p>Price per Unit: ${{ order_detail.product_size.price }}</p>
                            <p>Quantity: {{ order_detail.quantity }}</p>
                            <p>Total Price: ${{ order_detail.total_price }}</p>
                        </div>
                        <hr>
                        {% endfor %}
                        <div class="row">
                            <div class="col-md-4">
                                <h6>Total Price</h6>
                                <div>
                                    <strong style="color: rgb(249, 70, 70); font-size: 2rem;">
                                        <p>${{ total_price }}</p>
                                    </strong>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% else %}
            <div class="col-md-12">
                <h3>You must be signed in to view the checkout page.</h3>
            </div>
            {% endif %}
        </div>
    </div>

    
    <script>
        document.getElementById("orderButton").addEventListener("click", function () {
            // Show the form
            document.getElementById("orderForm").style.display = "block";
    
            // Hide the button
            document.getElementById("orderButton").style.display = "none";
        });
    </script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#cvccard').hide(); // Hide the element initially

        $('#cash').change(function () {
            if (this.checked) {
                $('#credit').prop('checked', false); // Uncheck the credit card checkbox
                $('#cvccard').hide(); // Hide the cvccard element
            } else {
                //   $('#cvccard').show(); // Show the cvccard element when the checkbox is unchecked
            }
        });

        $('#credit').change(function () {
            if (this.checked) {
                $('#cash').prop('checked', false); // Uncheck the cash checkbox
                $('#cvccard').show(); // Show the cvccard element when the credit card checkbox is checked
            } else {
                $('#cvccard').hide(); // Hide the cvccard element when the credit card checkbox is unchecked
            }
        });
        $("#order").click(function () {
            $(".notification-background").fadeIn();
            $("#alert").fadeIn();
        });

        $("#okButton").click(function () {
            $(".notification-background").fadeOut();
            $("#alert").fadeOut();
        });
    });

</script>
<script>
    function validatePayment() {
        const creditCheckbox = document.getElementById('credit');
        const cashCheckbox = document.getElementById('cash');

        if (!creditCheckbox.checked && !cashCheckbox.checked) {
            alert('Please select a payment method: Credit Card / Debit Card or Cash on Delivery.');
        } else {
            // Proceed with the purchase by submitting the form
            document.getElementById('orderForm').submit();
        }
    }
</script>

</body>
</html>

CafeShop/templates/Orderfolder/hottea.html
{% extends 'Orderfolder/ordermenu.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} hottea Page {% endblock title %}</title>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@700&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/ordercss/hottea.css' %}" />
</head>

<body>
    <div class="orderhead">
        <ul class="redirectory">
            <li><a href="{% url 'home:drinkpage' %}">
                    <h4>Menu /</h4>
                </a></li>
            <li><a href="{% url 'home:hotcoffee' %}">
                    <H4> Hot Coffee</H4>
                </a></li>
        </ul>

        <h2>Hot Coffees</h2>

        <div class="ordereviroment">
            <div class="port1">
                <h4>Americanos</h4>
                <hr style="color: #7D7A79;">
                <div class="b1">
                    <center>
                        <img src="{% static 'image/order/Screenshot 2023-08-26 234721.png' %}">
                        <p>Caffé Americano</p>
                    </center>

                </div>
            </div>


            <div class="port2">
                <h4>Brewed Coffees</h4>
                <hr style="color: #7D7A79;">
                <div class="cafeport">
                    <div class="b1">
                        <center>
                            <img src="{% static 'image/order/Screenshot 2023-08-26 234721.png' %}">
                            <p>Featured Blonde Roast</p>
                        </center>

                    </div>
                    <div class="b1">
                        <center>
                            <img src="{% static 'image/order/Screenshot 2023-08-26 234721.png' %}">
                            <p>Featyred Neduyn Riast
                                Pike Place Roast</p>
                        </center>

                    </div>

                    <div class="b1">
                        <center>
                            <img src="{% static 'image/order/Screenshot 2023-08-26 234721.png' %}">
                            <p>Featured Dark Roast
                                Sumatra</p>
                        </center>

                    </div>
                </div>

            </div>


            <div class="port3">
                <h4>Brewed Coffees</h4>
                <hr style="color: #7D7A79;">
                <div class="cafeport">
                    <div class="b1">
                        <center>
                            <img src="{% static 'image/order/Screenshot 2023-08-26 234721.png' %}">
                            <p>Featured Blonde Roast</p>
                        </center>

                    </div>
                    <div class="b1">
                        <center>
                            <img src="{% static 'image/order/Screenshot 2023-08-26 234721.png' %}">
                            <p>Featyred Neduyn Riast
                                Pike Place Roast</p>
                        </center>

                    </div>

                    <div class="b1">
                        <center>
                            <img src="{% static 'image/order/Screenshot 2023-08-26 234721.png' %}">
                            <p>Featured Dark Roast
                                Sumatra</p>
                        </center>

                    </div>
                </div>

            </div>


        </div>

    </div>


    {% endblock content %}
</body>

</html>

CafeShop/templates/Orderfolder/thank_you.html
<!-- thank_you.html -->
<h1>Thank You!</h1>
<p>Your order has been confirmed.</p>
<!-- Add any additional content or links you want here -->