CafeShop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls', namespace='menu')),
    path('', include('dashboard.urls')),
    path('', include('home.urls')),
    path('userprofile/', include('userprofile.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import include, re_path, path
from django.conf import settings 
from django.conf.urls.static import static
from django.views.generic import DetailView
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from dashboard import views as dashboard_view
from . import views
from dashboard.views import *

app_name = 'dashboard'
urlpatterns = [
    re_path('^dashboard/$', dashboard_view.dashboard, name='dashboard'),
    path('edit_product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('add_new_product/', views.add_new_product_view, name='add-new-product'),
    path('add_new_product/<int:product_id>/', add_new_product_view, name='add-new-product'),
    path('checkout_data/', views.checkout_view, name='checkout_data'),
    path('order-detail/', views.order_detail_view, name='order_detail'),
    path('User-Account/', views.display_customer_users, name='user-account'),




    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

home/urls.py
from django.urls import include, re_path, path
from django.conf import settings 
from django.conf.urls.static import static
from django.views.generic import DetailView
from django.contrib.auth import views as auth_views

from home import views as home_view
from . import views
from home.views import *

from userprofile import views as userprofile_view
from . import views
from userprofile.views import *

app_name = 'home'
urlpatterns = [
  re_path('^index/$', home_view.index, name='index'),
    re_path('^home/$', home_view.home, name='home'),
    re_path('^test/$', home_view.test, name='test'),
    re_path('^aboutus/$', home_view.aboutus, name='aboutus'),
    re_path('^findus/$', home_view.FindUs, name='findus'),
    re_path('^drinks/$',home_view.drinks,name='drinkpage'),
    re_path('^hottea/$',home_view.hottea,name='hotcoffee'),
    re_path('^profile/$', home_view.profile, name='profile'),
    re_path('^favoritedrinks/$', home_view.favdrink, name='favoritedrink'),
    re_path('^previousorder/$', home_view.previousorder, name='previousorder'),
    path('update_profile_picture/', views.update_profile_picture, name='update_profile_picture'),
    path('delete_profile_picture/', views.delete_profile_picture, name='delete_profile_picture'),
    # path('edit_user_info/', views.edit_user_info, name='edit_user_info'),
    # path('update_profile_info/', views.update_profile_info, name='update_profile_info'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

userprofile/urls.py
from django.urls import include, re_path
from django.conf import settings 
from django.conf.urls.static import static
from django.views.generic import *
from django.urls import path
from django.contrib.auth import views as auth_views

from userprofile import views as userprofile_view
from . import views
from userprofile.views import *

app_name = 'userprofile'    
urlpatterns = [
    re_path('^signin/$', SigninView.as_view(), name='signin'),
    re_path('signup/', SignupView.as_view(), name='signup'),
    re_path('^logout/$', LogoutView.as_view(), name='logout'),
    # re_path('^feature/$',)
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models
# Create your models here.

dashboard/views.py
from django.shortcuts import render
from userprofile.models import CustomerUser
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView 
from django.views import generic
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from menu.models import AddProduct, ProductSize, Size, OrderDetail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
import json
from django.http import HttpResponseRedirect
from django.urls import reverse 
from django.utils import timezone
from django.db.models import Q 
from django import forms
from menu.models import Checkout, OrderDetail, OrderItem, ProductSize, AddProduct, CartItem, ProductSize
from datetime import datetime 


def checkout_view(request):
    # Retrieve the checkout data with related OrderDetail data, ordered by checkout ID in descending order
    checkout_data = Checkout.objects.select_related('user', 'customer').prefetch_related(
        'order_items__product_size__product'
    ).order_by('-checkout_id')

    # Create a list to store organized data by unique checkout IDs
    unique_checkouts = []

    for checkout in checkout_data:
        unique_checkout = {
            'checkout_id': checkout.checkout_id,
            'username': checkout.user.username,
            'products': [],
            'total_price': 0,  # Initialize total price
            'order_date': checkout.order_date,  # Include the 'order_date' field
        }
        for order_item in checkout.order_items.all():
            product = order_item.product_size.product
            if product:  # Check if there is a product
                total_price = order_item.product_size.price * order_item.quantity
                unique_checkout['products'].append({
                    'product_name': product.product_name,
                    'size': order_item.product_size.size.get_size_display(),
                    'quantity': order_item.quantity,
                    'price_per_unit': order_item.product_size.price,
                    'total_price': total_price,
                })
                unique_checkout['total_price'] += total_price  # Update total price
        unique_checkouts.append(unique_checkout)

    # Pass the data to the template
    context = {'user_checkouts': unique_checkouts}
    return render(request, 'dashboard/admin/checkout_data.html', context)

def display_customer_users(request):
    customer_users = CustomerUser.objects.all()
    return render(request, 'dashboard/admin/useraccount.html', {'customer_users': customer_users})


@login_required
def dashboard(request):
    # Retrieve all products from the database
    products = AddProduct.objects.all()
    hot_drinks_count = AddProduct.objects.filter(product_name__icontains='Hot').count()
    iced_drinks_count = AddProduct.objects.filter(product_name__icontains='Iced').count()
    frappe_drinks_count = AddProduct.objects.filter(
        Q(product_name__icontains='Frappe') | Q(product_name__icontains='Milkshake')
    ).count()

    total_drinks_count = products.count()  # Total count of all drinks

    context = {
        'products': products,
        'hot_drinks_count': hot_drinks_count,
        'iced_drinks_count': iced_drinks_count,
        'frappe_drinks_count': frappe_drinks_count,
        'total_drinks_count': total_drinks_count,  # Add total drinks count to context
    }

    # Create a Paginator instance
    paginator = Paginator(products, 10)  # Show 5 products per page

    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver last page of results.
        products = paginator.page(paginator.num_pages)

    # Store the current page number in the session
    request.session['dashboard_current_page'] = products.number

    # Pass the paginated products and the context to the template
    context['products'] = products

    return render(request, 'dashboard/admin/dashboard.html', context)



def edit_product(request, product_id):
    product = get_object_or_404(AddProduct, id=product_id)

    if request.method == 'POST':
        # Retrieve the new category value from the POST data
        new_category = request.POST.get('category')

        # Update the product's category
        product.category = new_category

        # Save the updated product to the database
        product.save()

        # Get the size IDs from the POST data
        size_ids = request.POST.getlist('size_id')

        for size_id in size_ids:
            try:
                # Get the corresponding ProductSize instance
                product_size = ProductSize.objects.get(id=size_id)

                # Retrieve the new price value for the current size from the POST data
                new_price = request.POST.get(f'price_{size_id}')  # Assuming the input field names are 'price_[size_id]'

                # Update the product size price
                product_size.price = new_price

                # Save the updated product size to the database
                product_size.save()

            except ProductSize.DoesNotExist:
                messages.error(request, f"Product size with ID {size_id} not found.")

        # Add a success message
        messages.success(request, 'Changes saved successfully.')

        # Redirect to the product list page or another appropriate page
        return redirect('dashboard:dashboard')

    # Retrieve all possible category choices from the AddProduct model
    all_categories = [choice[1] for choice in AddProduct._meta.get_field('category').choices]

    # Retrieve all possible size choices from the Size model
    all_sizes = Size.SIZE_CHOICES

    return render(request, 'dashboard/admin/edit_product.html', {'product': product, 'all_categories': all_categories, 'all_sizes': all_sizes})


from django.views.decorators.csrf import csrf_exempt

@csrf_exempt  # Disable CSRF protection for this view
def delete_product(request, product_id):
    if request.method == 'POST':  # Change the request method to POST
        # Get the product object based on the product_id
        product = get_object_or_404(AddProduct, pk=product_id)

        # Perform the product deletion
        try:
            product.delete()
            return JsonResponse({'message': 'Product deleted successfully'})
        except Exception as e:
            return JsonResponse({'error': f'Error deleting product: {str(e)}'})

    # Return an error response for non-POST requests
    return JsonResponse({'error': 'Invalid request method'})

def add_new_product_view(request):
    sizes = Size.objects.all()  # Retrieve all size choices from the database
    # Retrieve category choices from the model
    category_choices = [(choice, choice) for choice, _ in AddProduct._meta.get_field('category').choices]

    if request.method == 'POST':
        product_name = request.POST.get('product_name')
        category = request.POST.get('category')

        # Create a new product using the data
        new_product = AddProduct(product_name=product_name, category=category)
        new_product.save()

        # Handle multiple sizes, prices, and images
        for size in sizes:
            size_id = request.POST.get(f'size_{size.id}')
            price = request.POST.get(f'price_{size.id}')
            image = request.FILES.get(f'image_{size.id}')

            if size_id and price:
                # Retrieve the Size instance based on the size_id
                size_instance = Size.objects.get(id=size_id)

                # Create the ProductSize instance with the Size instance
                product_size = ProductSize(product=new_product, size=size_instance, price=price, images=image)
                product_size.save()

        return redirect('dashboard:dashboard')  # Redirect to the dashboard home page

    context = {'sizes': sizes, 'category_choices': category_choices}
    return render(request, 'dashboard/admin/addproduct.html', context)


def order_detail_view(request):
    # Retrieve the order details and create a Paginator instance
    current_time = timezone.localtime(timezone.now())
    order_details = OrderDetail.objects.all()
    paginator = Paginator(order_details, 10)  # Show 10 items per page

    # Get the current page number from the request's GET parameters
    page_number = request.GET.get('page')

    # Get the Page object for the current page
    page = paginator.get_page(page_number)

    return render(request, 'dashboard/admin/order_detail.html', {'order_details': page, 'current_time': current_time})

CafeShop/templates/dashboard/admin/addproduct.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add New Product</title>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@700&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body{
        font-family: var(--primary-font);
        background-color: rgba(245, 242, 242, 0.863);
    }

        :root {
            --primary-font: "Quicksand", sans-serif;
            --secondary-font: "Poppins", sans-serif;
            --first-color: #fffdd0;
            --second-color: #a0522d;
        }
        .navbar-light .navbar-nav .active>.nav-link {
        color: white;
        transition: 0.5s ease;
    }
    .navbar-light .navbar-nav .active>.nav-link:hover {
        color:black;
    }

    .navbar-light .navbar-nav .nav-link {
        color: white;
        font-family: var(--primary-font);
        transition: 0.5s ease;
        font-size: 20px;
    }

    .navbar-light .navbar-brand {
        font-family: var(--primary-font);
        color: white;
        transition: 0.5s ease;

    }

    .navbar {
        background-color: var(--second-color);
        color: white;
    }

        a.go-back-btn {
            font-family: var(--primary-font);
            background-color: #A0522D;
            margin: 3vh 0 0 3vh;
            padding: 10px;
            border-radius: 10px;
            font-size: 20px;
            color: white;
            text-decoration: none;
            transition: 0.5s ease;
        }


        a.go-back-btn:hover {
            background-color: black;
            color: white;
        }
        .container {
            max-width: 600px;
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            padding: 30px;
            margin-top: 50px;
            margin-bottom: 15vh;
        }
        .form-group {
            margin-bottom: 20px;
        }
        nav {
            margin-bottom: 3vh;
        }
        button.btn-add-new{
            background-color: var(--second-color);
            border:none;
            transition: 0.3s ease-in-out;
            font-size: 20px;
        }
        button.btn-add-new:hover{
            background-color: green;
        }
    </style>
</head>

<body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="{% url 'dashboard:dashboard'%}">Dashboard</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link nav-color" href="{% url 'home:home'%}">Home <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-color" href="{% url 'dashboard:dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-color" href="#">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-color" href="{% url 'userprofile:logout' %}">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
    <a href="javascript:history.go(-1);" class="go-back-btn">Go Back</a>

    <div class="container">
        <h2 class="mb-4 text-center" style="color: var(--second-color);">Add New Product</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="product_name">Product Name:</label>
                <input type="text" class="form-control" id="product_name" name="product_name" required>
            </div>

            <div class="form-group">
                <label for="category">Category:</label>
                <select class="form-select custom-select" id="category" name="category" required>
                    <option value="" disabled selected>Select a category</option>
                    {% for choice in category_choices %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                    {% endfor %}
                </select>
            </div>

            {% for size in sizes %}
            <div class="form-group">
                <label for="size_{{ size.id }}">Size:</label>
                <select class="form-select custom-select" id="size_{{ size.id }}" name="size_{{ size.id }}">
                    <option value="{{ size.id }}">{{ size.get_size_display }}</option>
                </select>
            </div>

            <div class="form-group">
                <label for="price_{{ size.id }}">Price:</label>
                <input type="text" class="form-control" id="price_{{ size.id }}" name="price_{{ size.id }}">
            </div>

            <div class="form-group">
                <label for="image_{{ size.id }}">Choose Image:</label>
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="image_{{ size.id }}" name="image_{{ size.id }}"
                        onchange="updateFileName(this)">
                    <label class="custom-file-label" for="image_{{ size.id }}">Choose file</label>
                </div>
            </div>
            {% endfor %}

            <div class="text-center">
                <button type="submit" class="btn btn-primary btn-add-new">Add new product</button>
            </div>
        </form>
    </div>

    <!-- Include Bootstrap JS and jQuery (if needed) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        function updateFileName(input) {
            const label = input.nextElementSibling;
            const fileName = input.files[0].name;
            label.innerHTML = fileName;
        }
    </script>
</body>

</html>

CafeShop/templates/dashboard/admin/completed_orders.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Completed Orders</title>
</head>
<body>
    <h1>Completed Orders</h1>
    <table>
        <thead>
            <tr>
                <th>Username</th>
                <th>Product Name</th>
                <th>Size</th>
                <th>Quantity</th>
                <th>Total Price</th>
            </tr>
        </thead>
        <tbody>
            {% for completed_order in completed_orders_data %}
                <tr>
                    <td>{{ completed_order.user.username }}</td>
                    <td>{{ completed_order.product_size.product.product_name }}</td>
                    <td>{{ completed_order.product_size.size.get_size_display }}</td>
                    <td>{{ completed_order.quantity }}</td>
                    <td>{{ completed_order.total_price }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

CafeShop/templates/dashboard/admin/edit_product.html
<!DOCTYPE html>
<html>

<head>
    <title>Edit Product</title>
    <!-- Include Bootstrap CSS (You should have Bootstrap installed and configured) -->
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@700&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="path-to-bootstrap-css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="sweetalert2.all.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

</head>
    <style>
        
        :root {
        --primary-font: "Quicksand", sans-serif;
        --secondary-font: "Poppins", sans-serif;
        --first-color: #fffdd0;
        --second-color: #a0522d;
    }
    body{
        font-family: var(--primary-font);
        background-color: rgba(245, 242, 242, 0.863);
    }
        .form-group {
            margin-bottom: 20px;
        }

        a.go-back-btn {
        margin: 10vh 0 0 2vh;
        font-family: var(--primary-font);
        background-color: var(--second-color);
        padding: 10px;
        border-radius: 10px;
        color: white;
        text-decoration: none;
        transition: 0.5s ease;
    }

        a.go-back-btn:hover {
            background-color: black;
            color: white;
            border: none;
        }
        .navbar-light .navbar-nav .active>.nav-link {
        color: white;
        transition: 0.5s ease;
    }
    .navbar-light .navbar-nav .active>.nav-link:hover {
        color:black;
    }

    .navbar-light .navbar-nav .nav-link {
        color: white;
        font-family: var(--primary-font);
        transition: 0.5s ease;
        font-size: 20px;
    }

    .navbar-light .navbar-brand {
        font-family: var(--primary-font);
        color: white;
        transition: 0.5s ease;
    }

    .navbar {
        background-color: var(--second-color);
        color: white;
    }
        nav {
            margin-bottom: 8vh;
        }
        .form-group img{
            display: flex;
            margin: 0 auto;
            max-width: 300px; 
            max-height: 300px;
            border-radius: 20px;
        }
        /* Center the container */
        .center-container {
            margin-top: 10vh;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh; /* Adjust the height as needed */
            margin-bottom: 30vh;
        }

        .custom-container {
            background-color: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
            width:40%;
            
        }
        h1.mt-4{
            text-align: center;
        }
        h1.product-name{
            color:var(--second-color);
        }
        form{
            font-size: 25px;
            padding: 30px;
        }
        input.form-control {
        font-size: 22px; 
    }
        button.btn-save-change{
            background-color: var(--second-color);
            border: none;
            font-size: 20px;
            transition: 0.3s ease-in;
        }
        button.btn-save-change:hover{
            background-color: green;
        }
    </style>


<body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="{% url 'dashboard:dashboard'%}">Dashboard</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link nav-color" href="{% url 'home:home'%}">Home <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-color" href="{% url 'dashboard:dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-color" href="#">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-color" href="{% url 'userprofile:logout' %}">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
    <a href="javascript:history.go(-1);" class="go-back-btn">Go Back</a>




    <div class="center-container">
        <div class="custom-container">
            <h1 class="mt-4">Edit Drink: </h1>
            <h1 class="mt-4 product-name">{{ product.product_name }}</h1>
            <form method="post" enctype="multipart/form-data" action="{% url 'dashboard:edit_product' product.id %}">
                {% csrf_token %}
            
                <!-- Product Image -->
                <div class="form-group">
                    <label for="current_image"></label>
                    {% if product.sizes.first.images %}
                    <img src="{{ product.sizes.first.images.url }}" alt="{{ product.product_name }} Image">
                    {% else %}
                    <p>No Image</p>
                    {% endif %}
                </div>
            
                <!-- Product Name -->
                <div class="form-group">
                    <label for="name">Product Name:</label>
                    <input type="text" id="name" name="name" class="form-control" value="{{ product.product_name }}">
                </div>
            
                <!-- Category Selection -->
                <div class="form-group">
                    <label for="category">Category:</label>
                    <select name="category" id="category" class="form-control">
                        <option value="">Select a category</option>
                        {% for category in all_categories %}
                        <option value="{{ category }}" {% if category == product.category %}selected{% endif %}>
                            {{ category }}
                        </option>
                        {% endfor %}
                    </select>
                </div>
            
                {% for size in product.sizes.all %}
                <div class="form-group">
                    <label for="size_{{ size.id }}">{{ size.size.get_size_display }}:</label>
                    <input type="hidden" name="size_id" value="{{ size.id }}">
                    $
                    <input type="text" id="size_{{ size.id }}" name="price_{{ size.id }}" class="form-control"
                        value="{{ size.price }}">
                </div>
                {% endfor %}
            
                <input type="hidden" name="next" value="{{ products.number }}">
            
                <!-- Add other form fields for editing product details -->
            
                <button type="submit" class="btn btn-primary btn-save-change">Save Change</button>
            </form>
        </div>
    </div>
    <input type="hidden" id="successParam" name="successParam" value="false">

    <!-- Bootstrap Success Modal -->
    <div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Success!</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Change saved successfully.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>





<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="path-to-jquery/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="path-to-bootstrap-js/bootstrap.min.js"></script>
    <script>
    // $("#saveChangeButton").on("click",function(){
    //     swal("Good job!", "You clicked the button!", "success");
    // })
        //$(document).ready(function () {
//             $("#saveChangeButton").on("click",function(){
//                 swal("Good job!", "You clicked the button!", "success");
    
// })

//             })
//             // Check if the successParam is set to 'true'
//             const successParam = new URLSearchParams(window.location.search).get('success');
    
//             // Add a click event handler for the "Save change" button
//             $('.btn-save-change').click(function (event) {
//                 event.preventDefault(); // Prevent the default form submission
    
//                 // Manually submit the form
//                 $('form').submit();
//             });
    
//             // If successParam is 'true', show the modal
//             if (successParam === 'true') {
//                 $('#successModal').modal('show');
//             }
//         });
    </script>
    
    
<!--     
    

    <script>
        function goBack() {
            // Use window.history to navigate back to the previous page
            window.history.back();
        }
    </script> -->
</body>

</html>