CafeShop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls', namespace='menu')),
    path('', include('dashboard.urls')),
    path('', include('home.urls')),
    path('userprofile/', include('userprofile.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import include, re_path, path
from django.conf import settings 
from django.conf.urls.static import static
from django.views.generic import DetailView
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from dashboard import views as dashboard_view
from . import views
from dashboard.views import *

app_name = 'dashboard'
urlpatterns = [
    re_path('^dashboard/$', dashboard_view.dashboard, name='dashboard'),
    path('edit_product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('add_new_product/', views.add_new_product_view, name='add-new-product'),
    path('add_new_product/<int:product_id>/', add_new_product_view, name='add-new-product'),
    path('checkout_data/', views.checkout_view, name='checkout_data'),
    path('order-detail/', views.order_detail_view, name='order_detail'),
    path('User-Account/', views.display_customer_users, name='user-account'),




    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

home/urls.py
from django.urls import include, re_path, path
from django.conf import settings 
from django.conf.urls.static import static
from django.views.generic import DetailView
from django.contrib.auth import views as auth_views

from home import views as home_view
from . import views
from home.views import *

from userprofile import views as userprofile_view
from . import views
from userprofile.views import *

app_name = 'home'
urlpatterns = [
  re_path('^index/$', home_view.index, name='index'),
    re_path('^home/$', home_view.home, name='home'),
    re_path('^test/$', home_view.test, name='test'),
    re_path('^aboutus/$', home_view.aboutus, name='aboutus'),
    re_path('^findus/$', home_view.FindUs, name='findus'),
    re_path('^drinks/$',home_view.drinks,name='drinkpage'),
    re_path('^hottea/$',home_view.hottea,name='hotcoffee'),
    re_path('^profile/$', home_view.profile, name='profile'),
    re_path('^favoritedrinks/$', home_view.favdrink, name='favoritedrink'),
    re_path('^previousorder/$', home_view.previousorder, name='previousorder'),
    path('update_profile_picture/', views.update_profile_picture, name='update_profile_picture'),
    path('delete_profile_picture/', views.delete_profile_picture, name='delete_profile_picture'),
    # path('edit_user_info/', views.edit_user_info, name='edit_user_info'),
    # path('update_profile_info/', views.update_profile_info, name='update_profile_info'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

menu/urls.py
from django.urls import include, re_path
from django.conf import settings 
from django.conf.urls.static import static
from django.views.generic import *
from django.urls import path
from django.contrib.auth import views as auth_views

from menu import views as menu_view
from . import views
from menu.views import *



app_name = 'menu'
urlpatterns = [
    re_path('menu/', views.menu, name='menu'),
    path('drink_details/<int:product_id>/', views.drink_details, name='drink_details'),
    path('order-details/', views.order_detail_list, name='order_detail_list'),
    path('order-details/<int:order_detail_id>/', views.order_detail_detail, name='order_detail_detail'),
    path('iced-drinks/', views.iced_drinks, name='IcedDrink'),
    path('hot-drinks/', views.hot_drinks, name='HotDrink'),
    path('frappe-drinks/', views.frappe_drinks, name='FrappeDrink'),
    path('add_to_order/', views.add_to_order, name='add_to_order'),
    path('cart/', views.cart, name='cart'),
    path('user_detail/', views.user_detail, name='user_detail'),
    path('checkout/', views.checkout, name='checkout'),
    path('confirm_order/', views.confirm_order, name='confirm_order'),
    path('order_confirmation/', views.order_confirmation_page, name='order_confirmation_page'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('continue-to-order/', views.continue_to_order, name='continue_to_order'),
    path('remove_product_from_order/<int:cart_item_id>/', views.remove_product_from_order, name='remove_product_from_order'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import include, re_path
from django.conf import settings 
from django.conf.urls.static import static
from django.views.generic import *
from django.urls import path
from django.contrib.auth import views as auth_views

from userprofile import views as userprofile_view
from . import views
from userprofile.views import *

app_name = 'userprofile'    
urlpatterns = [
    re_path('^signin/$', SigninView.as_view(), name='signin'),
    re_path('signup/', SignupView.as_view(), name='signup'),
    re_path('^logout/$', LogoutView.as_view(), name='logout'),
    # re_path('^feature/$',)
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CafeShop/templates/menufolder/location.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} Home {% endblock title %}</title>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@700&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>
<style>
    :root {
    --primary-font: "Quicksand", sans-serif;
    --secondary-font: "Poppins", sans-serif;
    --first-color: #fffdd0;
    --second-color: #a0522d;
}
    p.welcome-message:hover{
        text-decoration: underline;
        color: var(--second-color);
    }
    .welcome-message{
        margin:5px 10px 0 10px;
    }
    span.username{
        color:var(--second-color);
    }
    .mapouter {
        position: relative;

        width:100%;
        height: 100vh; 
    }

    .gmap_canvas {
        display: inline-block;
        overflow: hidden;
        background: none !important;
        width: 100%;
        height: 1080px;
        margin: 0 auto; /* This centers the map horizontally */
    }
    iframe{
            width: 100%;
            height: 100%;
            border: 0;
    }
    .btn-primary{
        margin:0 10px;
    }
    .btn-signin{
        background-color: transparent;
        border: 1px solid black;
    }
    .btn-signup{
        background-color: var(--second-color);
        border: 1px solid white;
    }
    a.btn-signup {
        color:white;
    }
    .btn-primary {
        margin: 0 10px;
    }

    .btn-signin {
        background-color: transparent;
        border: 1px solid black;
        transition: 0.2s ease;
    }

    .btn-signin:hover {
        background-color: var(--first-color);
        border: 1px solid black;
        color: #000;
    }

    .btn-signup {
        background-color: var(--second-color);
        border: 1px solid white;
        transition: 0.2s ease;
    }

    .btn-signup:hover {
        background-color: rgb(194, 116, 47);
        color: #ffffff;
    }

    a.btn-signup {
        color: white;
        margin: 0 5px;
    }

    a.btn-signup:hover {
        color: white;
    }
    .cart-icon {
        position: relative;
    }

    .cart-dot {
        position: absolute;
        top: 5px;
        /* Adjust the top position as needed */
        right: 5px;
        /* Adjust the right position as needed */
        width: 10px;
        height: 10px;
        background-color: red;
        border-radius: 50%;
        display: inline-block;
    }

    a.cart-icon {
        border-radius: 20px;
        width: 110px;
        transition: 0.5s ease;

    }

    a.cart-icon:hover {
        background-color: var(--second-color);

    }

    span.cart-count {
        transition: 0.5s ease;
        color: white;
        background-color: red;
        border-radius: 50%;
    }

    span.cart-count:hover {
        color: white;
    }

    a.cart-icon img.cart-image-hover {
        display: none;

    }

    a.cart-icon:hover img.cart-image {
        display: none;

    }

    a.cart-icon:hover img.cart-image-hover {
        display: inline;

    }

</style>
<body>
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a href="{% url 'home:home' %}">
                <img src="{% static 'image/logo/image-removebg-preview__2__auto_x2-removebg-preview.png' %}"
                    class="navbar-brand" alt="Logo" />
            </a>
            <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarItems"
                aria-controls="navbarItems" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarItems">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                    <!-- If the user is logged in, take them to 'home:home' -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:home' %}">Home</a>
                    </li>
                    {% else %}
                    <!-- If the user is not logged in, take them to 'home:index' -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:index' %}">Home</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'menu:menu' %}">Menu</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:aboutus' %}">About us</a>
                    </li>
                    {% if user.is_superuser %}
                    <!-- Show the Dashboard link only for superusers -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dashboard:dashboard' %}">Dashboard</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <div class="d-flex">
                {% if user.is_authenticated %}
                <p class="welcome-message">
                    <a href="{% url 'home:profile' %}">{{ user.username }}</a>
                </p>
                <a href="{% url 'userprofile:logout' %}" class="btn btn-secondary">Logout</a>
                {% else %}
                <a href="{% url 'userprofile:signin' %}" class="btn btn-secondary btn-signin">Sign in</a>
                <a href="{% url 'userprofile:signup' %}" class="btn btn-secondary btn-signup">Sign Up</a>
                {% endif %}
                <a href="{% url 'home:findus' %}" class="btn">Find us</a>
            </div>
            <a href="{% url 'menu:cart' %}" class="cart-icon">
                <span class="cart-icon-svg">
                    <img src="{% static 'image/logo/icons8-cart-48 brown.png' %}" alt="Cart Icon" class="cart-image">
                    <img src="{% static 'image/logo/icons8-cart-48 white.png' %}" alt="Cart Icon" class="cart-image-hover">
                </span>
                {% if cart_count > 0 %}
                    <span class="badge badge-pill badge-danger cart-count">{{ cart_count }}</span>
                {% endif %}
            </a>
        </div>
    </nav>

    <div class="mapouter">
        <div class="gmap_canvas">
            <iframe src="https://maps.google.com/maps?q=Starbuck%20BKK&amp;t=&amp;z=16&amp;ie=UTF8&amp;iwloc=&amp;output=embed" id="gmap_canvas" frameborder="0" scrolling="no"></iframe>
        </div>
    </div>

    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            const redDot = document.getElementById('red-dot');
    
            // Check if there are products in the order
            const cartCount = parseInt("{{ cart_count }}");
            if (cartCount === 0) {
                redDot.style.display = 'none';
            }
        });
    </script>
    {% block content %}{% endblock content %}
</body>

</html>

CafeShop/templates/menufolder/menu2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} Home {% endblock title %}</title>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@700&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- <link rel="stylesheet" href="{% static 'css/styles.css' %}" /> -->
</head>
<style>
    * {
  padding: 0;
  margin: 0;
}
p.welcome-message:hover{
        text-decoration: underline;
    }

:root {
  --primary-font: "Quicksand", sans-serif;
  --secondary-font: "Poppins", sans-serif;
  --first-color: #fffdd0;
  --second-color: #a0522d;
}
#divinfo{
  max-height: 4100;
}
.navbar {
  font-family: var(--primary-font);
  font-size: 20px;
  background-color: #ffffff;
  color: #000000;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px;
  letter-spacing: 2px;
}

nav {
  box-shadow: rgba(17, 17, 26, 0.1) 0px 1px 0px;
}

#body {
  display: flex;
  justify-content: center;
  align-items: center;
  max-width: 50%;
  margin: auto;
  flex-direction: column;
  padding: 5% 0;
}

#body #row1 {
  display: flex;
  /* width: 100%; */
  padding-bottom: 4%;
}

#body #row1 #divimg {
  width: 50%; 
}

#body #row1 #divimg img {
  width: 100%;
  background-color: #a0522d;
}
#divinfo{
  width: 50%;
  text-align: center;
  background-color: #FEDF00;
}
#body #row1 #divinfo {
  width: 50%;
  text-align: center;
  background-color: #FEDF00;
  padding: 10% 2%;
}

#body #row1 #divinfo h1 {
  color: #a0522d;

}

#body #row1 #divinfo input {
  padding: 1% 5%;
  border-radius: 20px;
  border: 2px solid #a0522d;
  background-color: #FEDF00;
}



#body #row2 {
  display: flex;
  width: 100%;
  padding-bottom: 4%;
}

#body #row2 #divimg2 {
  width: 50%;
  order: 2;
}

#body #row2 #divimg2 img {
  width: 100%;
  background-color: #a0522d;
}

#body #row2 #divinfo2 {
  color: white;
  width: 50%;
  text-align: center;
  background-color: #a0522d;
  padding: 10% 2%;
  order: 1;
}

#body #row2 #divinfo2 input {
  padding: 1% 5%;
  border-radius: 20px;
  border: 2px solid white;
  background-color: #a0522d;
  color: #ffffff;
}




#body #row3 {
  display: flex;
  width: 100%;
  padding-bottom: 4%;
}

#body #row3 #divimg3 {
  width: 50%;
}

#body #row3 #divimg3 img {
  width: 100%;
  background-color: #a0522d;
}

#body #row3 #divinfo3 {
  width: 50%;
  text-align: center;
  background-color: #FEDF00;
  padding: 10% 2%;
}

#body #row3 #divinfo3 h1 {
  color: #a0522d;

}

#body #row3 #divinfo3 input {
  padding: 1% 5%;
  border-radius: 20px;
  border: 2px solid #a0522d;
  background-color: #FEDF00;
}



#body #row4 {
  display: flex;
  width: 100%;
  padding-bottom: 4%;
}

#body #row4 #divimg4 {
  width: 50%;
}

#body #row4 #divimg4 img {
  width: 100%;
  background-color: #a0522d;
}

#body #row4 #divinfo4 {
  color: white;
  width: 50%;
  text-align: center;
  background-color: #a0522d;
  padding: 10% 2%;
}

#body #row4 #divinfo4 input {
  padding: 1% 5%;
  border-radius: 20px;
  border: 2px solid white;
  background-color: #a0522d;
  color: #ffffff;
}









.navbar-brand {
  width: 60px;
}

.navbar a {
  color: #000000;
  text-decoration: none;
  padding: 10px;
}

.navbar a:hover {
  color: var(--second-color);
}

.navbar-logo {
  margin-right: auto;
}


li.nav-item a.nav-link {
  margin-left: 20px;
}

.navbar-collapse ul li.nav-item a.nav-link {
  margin-left: 20px;
}

.navbar-buttons {
  display: flex;
  align-items: center;
}

.menu-btn {
  display: none;
}

.navbar-toggler {
  transition: margin-left 0.3s ease;
}

.navbar-items {
  display: flex;
  flex-direction: column;
  /* Add any other initial styles here */
}

.d-flex a.btn {
  border-radius: 50px;
}

.d-flex a.btn {
  font-size: 15px;
}

.d-flex a.btn-sign-in {
  border: 1px solid #000;
  margin: 0 10px;
  transition: 0.2s ease-in;
}

.d-flex a.btn-sign-in:hover {
  background-color: var(--first-color);
  color: #000;
}

.d-flex a.btn-sign-up {
  background-color: var(--second-color);
  margin: 0 10px;
  padding: 10px 15px;
  transition: 0.2s ease;
  color: #ffffff;
}

.d-flex a.btn-sign-up:hover {
  background-color: rgb(194, 116, 47);
  color: #ffffff;
}

.navbar-items.show {
  margin-left: 0;
  /* Set the desired margin for the expanded state */
}

@media screen and (max-width: 1745px) {
  #row1 {
    flex-direction: column;
  }

  .navbar-items {
    display: none;
    flex-direction: column;
  }

  #body #row1 #divimg {
    width: 100%;
  }

  #body #row1 #divinfo {
    width: 100%;
  }

  #row2 {
    flex-direction: column;
  }

  #body #row2 #divimg2 {
    width: 100%;
    order: 1;
  }

  #body #row2 #divinfo2 {
    width: 100%;
    order: 2;
  }


  #row3 {
    display: flex;
    flex-direction: column;
  }

  #body #row3 #divimg3 {
    width: 100%;
  }

  #body #row3 #divinfo3 {
    width: 100%;
  }


  #row4 {
    flex-direction: column;
  }

  #body #row4 #divimg4 {
    width: 100%;
    order: 1;
  }

  #body #row4 #divinfo4 {
    width: 100%;
    order: 2;
  }


  .navbar-items.show {
    display: flex;
  }

  .navbar-items a {
    padding: 10px 20px;
  }

  .navbar-buttons {
    display: none;
  }

  .menu-btn {
    display: block;
  }
}

footer {

  padding: 20px;
  font-family: var(--primary-font);
}

.ctn {
  width: 100%;
  max-width: 960px;
  margin: 0 auto;
}

.row {
  margin-bottom: 20px;
}

.col-md-4 h3 {
  text-align: left;
  font-size: 20px;

}

.col-md-4 {
  text-align: left;
  display: block;
  color: grey;
  width: 23.33%;
  float: left;
  border: 2px solid;
}

/* .col-md-4 ul{
  list-style-type: none;
  text-align: left;
  font-family: var(--secondary-font);
}
.col-md-4 li{
  text-decoration: none;
  width:180px;
  text-align: left;
  margin-top: 2vh;
} */
.col-md-4 a {
  width: 70%;
  text-decoration: none;
  color: grey;
  transition: 0.5s ease;
  font-size: 5px;
  display: block;
  margin: 20px 0 20px 0;
}

.col-md-4 a:hover {
  color: #000;
}

@media (max-width: 960px) {
  .ctn {
    width: 100%;
  }

  .row {
    flex-wrap: wrap;

  }

  .col-md-4 {
    width: 100%;
    margin-bottom: 20px;

  }

  .col-md-4 h3 {
    text-align: center;

  }

  .col-md-4 a {
    width: 100%;
    font-size: 2px;
    text-align: center;
  }
}
footer{
    width: 100vw;

    padding: 4% 0% 6% 3%;
}
footer .col{
    width: 100%;
    border-top:1px solid #9B8888 ;
    border-bottom:1px solid #9B8888 ;
    display: flex;
    padding: 4% 0% 6% 3%;
    margin-bottom: 5px;
}
footer .col .col2{
    margin-left: 5%;
}
footer .col .col3{
    margin-left: 5%;
}
footer .col .col4{
    margin-left: 5%;
}
footer .col .col5{
    margin-left: 5%;
}

footer .col h2{
    color: #A0522D;
}
footer .footericon {
    display: flex;
    margin-top: 2%;
}
footer .footericon img{
    width: 35px;
    height: 35px;
    border-radius: 50%;

    margin-left: 25px;
}
footer .footerlink ul{
    list-style: none;
    display: flex;
    width: 100%;
    margin-top: 4%;
}
footer .footerlink ul li a{
    color:  black;
    text-decoration: none;
    margin-right: 25px;
}
footer p{
    color: #A0522D;
    margin-top: 4%;
    margin-left: 25px;
}

</style>
<body>
  
  <nav class="navbar navbar-expand-lg">
    <div class="container">
        <a href="{% url 'home:home' %}">
            <img src="{% static 'image/logo/image-removebg-preview__2__auto_x2-removebg-preview.png' %}"
                class="navbar-brand" alt="Logo" />
        </a>
        <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarItems"
            aria-controls="navbarItems" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarItems">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <!-- If the user is logged in, take them to 'home:home' -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:home' %}">Home</a>
                </li>
                {% else %}
                <!-- If the user is not logged in, take them to 'home:index' -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:index' %}">Home</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'menu:menu' %}">Menu</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:aboutus' %}">About us</a>
                </li>
                {% if user.is_superuser %}
                <!-- Show the Dashboard link only for superusers -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:dashboard' %}">Dashboard</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="d-flex">
            {% if user.is_authenticated %}
            <p class="welcome-message">
                <a href="{% url 'home:profile' %}">{{ user.username }}</a>
            </p>
            <a href="{% url 'userprofile:logout' %}" class="btn btn-secondary">Logout</a>
            {% else %}
            <a href="{% url 'userprofile:signin' %}" class="btn btn-secondary btn-signin">Sign in</a>
            <a href="{% url 'userprofile:signup' %}" class="btn btn-secondary btn-signup">Sign Up</a>
            {% endif %}
            <a href="{% url 'home:findus' %}" class="btn">Find us</a>
        </div>
        <a href="{% url 'menu:cart' %}" class="cart-icon">
            <span class="cart-icon-svg">
                <img src="{% static 'image/logo/icons8-cart-48 brown.png' %}" alt="Cart Icon" class="cart-image">
                <img src="{% static 'image/logo/icons8-cart-48 white.png' %}" alt="Cart Icon" class="cart-image-hover">
            </span>
            {% if cart_count > 0 %}
                <span class="badge badge-pill badge-danger cart-count">{{ cart_count }}</span>
            {% endif %}
        </a>
    </div>
</nav>
    {% block main %}
    {% endblock main %}
 

        <!-- /main body -->

      
        <footer>
            <div class="col">
                <div class="col1">
                    <h2>Careers</h2>
                <p>Culture and Values</p>
                <p>Inclusion, Diversity <br>, and
                    Equity</p>
                    <p>College Achievement
                        Plan</p>
                        <p>Alumni Community</p>
                        <p>International Careers</p>
                </div>
                
                <div class="col2">
                    <h2>People</h2>
                    <p>Planet</p>
                    <p>Environmental and
                       Social  <br> Impact  Reporting
                        </p>
                        
                </div>
    
                <div class="col3">
                    <h2>For Business Partners</h2>
                <p>Landlord Support
                    Center</p>
                <p>Suppliers
                    </p>
                    <p>Corporate Gift Card
                        Sales
                        </p>
                        <p>Office and Foodservice
                            Coffee</p>
    
                </div>
    
                <div class="col4">
                    <h2>Order and Pick Up</h2>
                <p>Order on the App</p>
                <p>Order on the Web
                    </p>
                    <p>Delivery
                        </p>
                        <p>Order and Pick Up
                            Options</p>
                        <p>Explore and Find Coffee
                            for Home</p>
                </div>
            </div>
            <div class="footericon">
                <img src="{% static 'image/footer/fbicon.png' %}" alt="">
                <img src="{% static 'image/footer/igicon.png' %}" alt="">
                <img src="{% static 'image/footer/pinteresticon.png' %}" alt="">
                <img src="{% static 'image/footer/twittericon.png' %}" alt="">
                <img src="{% static 'image/footer/yticon.png' %}" alt="">
            </div>
            <div class="footerlink">
                <ul>
                    <li><a href="#">Privacy Notice  |</a></li>
                    <li><a href="#">Term of Use  |  </a></li>
                    <li><a href="#">Do Not Share My Personal Information |</a></li>
                    <li><a href="#">CA Supply Chain Act |</a></li>
                    <li><a href="#">Cookie Preferences |</a></li>
                </ul>
            </div>
            
            <p>© 2023 Starbucks Coffee Company. All rights reserved.</p>
        </footer>
        {% block scripts %}
        {% endblock scripts %}
    <script src="{% static 'js/scripts.js' %}"></script>
    {% block content %}{% endblock content %}
</body>

</html>